---
# Basic provisioning example
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: Create an EC2 instance for rstudio
    ec2:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      key_name: "{{ key_name }}"
      aws_region: "{{ aws_region }}"
      group: default,ssh-aria
      instance_type: m4.2xlarge
      image: "{{ ami_id }}"
      wait: yes
      private_ip: "{{ rstudio_private_ip }}"
      zone: "{{ zone }}"
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 100
          delete_on_termination: true
      instance_tags:
         Name: rstudio-server
      exact_count: 1
      count_tag: 
        Env: rstudio-server
        Name: rstudio-server
    register: ec2

