---
- name: install R
  command: yum --enablerepo=epel install R
wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
:w
yum install -y ./epel-release-latest-7.noarch.rpm
 yum repolist all
yum -y update
yum install -y R

wget https://download2.rstudio.org/rstudio-server-rhel-pro-1.1.419-x86_64.rpm
yum install -y rstudio-server-rhel-pro-1.1.419-x86_64.rpm
rstudio-server license-manager activate M6DI-93CV-J33G-9MWG-2YM9-57XI-7STA
change hostname
ichange date zone
sudo rm /etc/localtime 
ln -s /usr/share/zoneinfo/America/Chicago /etc/localtime
sudo sh -c 'echo "badm-r.business.illinois.edu" > /etc/hostname'
sudo hostname -F /etc/hostname

- name: run jupyterhub
  command: /usr/local/bin/docker-compose up -d jupyterhub

- name: wait for jupyterhub to start
  command: docker logs centos_jupyterhub_1
  register: jpy_status
  until: jpy_status.stderr.find("JupyterHub is now running") != -1
  retries: 5
  delay: 5

- name: get a jupyterhub api token
  command: docker exec centos_jupyterhub_1 jupyterhub token -f /srv/jupyterhub_config/jupyterhub_config.py {{ jupyterhub_admin_user }}
  register: jpy_api_token

- name: start remaining services
  shell: JPY_API_TOKEN={{ jpy_api_token.stdout }} JUPYTERHUB_API_TOKEN={{ jpy_api_token.stdout }} /usr/local/bin/docker-compose up -d --no-recreate
