---
# Create deploy, rstudio, and proxy servers
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars.yml
  tags:
    - create_instances
  tasks:
  - name: Create an EC2 instance for rstudio
    ec2:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      key_name: "{{ key_name }}"
      aws_region: "{{ aws_region }}"
      group: default
      instance_type: m4.2xlarge
      image: "{{ ami_id }}"
      wait: yes
      private_ip: "{{ rstudio_private_ip }}"
      zone: "{{ zone }}"
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 100
          delete_on_termination: true
      instance_tags:
         Name: rstudio-server
      exact_count: 1
      count_tag: rstudio-server
    register: ec2
  - name: Create an EC2 instance for deploy
    ec2:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      key_name: "{{ key_name }}"
      aws_region: "{{ aws_region }}"
      group: default,ssh-aria
      instance_type: t2.micro
      image: "{{ ami_id }}"
      wait: yes
      private_ip: "{{ deploy_private_ip }}"
      zone: "{{ zone }}"
      instance_tags:
         Name: deploy-server
      exact_count: 1
      count_tag: deploy-server
    register: ec2
  - name: Create an EC2 instance for proxy
    ec2:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      key_name: "{{ key_name }}"
      aws_region: "{{ aws_region }}"
      group: default
      instance_type: t2.micro
      image: "{{ ami_id }}"
      wait: yes
      private_ip: "{{ proxy_private_ip }}"
      zone: "{{ zone }}"
      instance_tags:
         Name: proxy-server
      exact_count: 1
      count_tag: proxy-server
    register: ec2

